source "%val{config}/plugins/plug.kak/rc/plug.kak"

plug 'andreyorst/plug.kak' noload
plug 'andreyorst/fzf.kak'
plug 'alexherbo2/auto-pairs.kak'
plug "ul/kak-lsp" config %{
    set-option global lsp_diagnostic_line_error_sign '║'
    set-option global lsp_diagnostic_line_warning_sign '┊'

    define-command ne -docstring 'go to next error/warning from lsp' %{ lsp-find-error --include-warnings }
    define-command pe -docstring 'go to previous error/warning from lsp' %{ lsp-find-error --previous --include-warnings }
    define-command ee -docstring 'go to current error/warning from lsp' %{ lsp-find-error --include-warnings; lsp-find-error --previous --include-warnings }

    define-command lsp-restart -docstring 'restart lsp server' %{ lsp-stop; lsp-start }

    hook global WinSetOption filetype=(go|elm) %{
        set-option window lsp_auto_highlight_references true
        set-option window lsp_hover_anchor false
        lsp-auto-hover-enable
        lsp-enable-window
    }

    hook global KakEnd .* lsp-exit
}


add-highlighter global/ number-lines

colorscheme base16

hook global WinCreate .* %{
	# auto-pairs-enable
}
set global disabled_hooks '.+-indent'
hook global ModeChange ".*:normal" %{ face global PrimaryCursor black,white+fg }
hook global ModeChange ".*:insert" %{ face global PrimaryCursor black,green+fg }

map global normal <c-p> ': fzf-mode<ret>'

