source "%val{config}/plugins/plug.kak/rc/plug.kak"

plug 'andreyorst/plug.kak' noload
plug 'ul/kak-lsp'
plug 'andreyorst/fzf.kak'
plug 'alexherbo2/auto-pairs.kak'

add-highlighter global/ number-lines

colorscheme base16

hook global WinCreate .* %{
      auto-pairs-enable
      lsp-enable
}

hook global ModeChange ".*:normal" %{ face global PrimaryCursor black,white+fg }
hook global ModeChange ".*:insert" %{ face global PrimaryCursor black,green+fg }

map global normal <c-p> ': fzf-mode<ret>'
